name: App CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm


      - name: Install Dependencies
        run: npm ci


      # -------------------------
      # Phase 4 - Lint
      # -------------------------
      - name: Run Lint
        run: npm run lint:ci


      # -------------------------
      # Phase 6 - Dependency Scan
      # -------------------------
      - name: Generate npm Audit Report
        run: |
          npm audit --json > audit-report.json || true


      - name: Upload Audit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit-report.json


      - name: Fail on Critical Vulnerabilities
        run: npm audit --audit-level=critical


  
      # Phase 7 - Unit Tests + Coverage
      # -------------------------
      - name: Run Unit Tests with Coverage
        run: npm run test:ci

      - name: Check for lcov.info
        run: |
          if [ -f coverage/lcov.info ]; then
            echo "lcov.info found!"
          else
            echo "lcov.info NOT found. Listing directory:"
            ls -R coverage
          fi

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: coverage/

      # -------------------------
      # Phase 8 - SonarCloud Analysis
      # -------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io


      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        continue-on-error: true   # مؤقت - عشان مشروع التخرج
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

            # -------------------------
      # Phase 9 - Docker Build
      # -------------------------

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: frontend

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # -------------------------
      # Phase 10 - SBOM
      # -------------------------

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM
        run: |
          syft frontend:${{ github.sha }} \
            -o spdx-json=frontend-sbom.spdx.json

      - name: Upload Frontend SBOM
        uses: actions/upload-artifact@v4
        with:
          name: frontend-sbom
          path: frontend-sbom.spdx.json
      

            # -------------------------
      # Phase 11 - Trivy Scan
      # -------------------------

      - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: frontend:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1

      # -------------------------
      # Phase 12 - Upload SARIF
      # -------------------------

      - name: Upload Trivy SARIF Report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-trivy-report
          path: trivy-results.sarif